spring:
#  config for GlobalErrorHandler
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
# H2 DB
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    # http://localhost:8080/h2-console
    console.enabled: true


regex-patterns:
  # OWASP email validation
  email: ^[a-zA-Z0-9_+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$
  # Minimum eight characters, at least one letter, one number and one special character
  password: ^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$