CREATE TABLE USERS
(
    ID         UUID PRIMARY KEY,
    NAME       VARCHAR(100)        NOT NULL,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    CREATED    TIMESTAMP,
    MODIFIED   TIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    TOKEN      VARCHAR(255),
    ACTIVE     BOOLEAN
);


CREATE TABLE PHONE
(
    ID         UUID PRIMARY KEY,
    USER_ID    UUID    NOT NULL,
    NUMBER INTEGER NOT NULL,
    CITY_CODE   TINYINT NOT NULL,
    COUNTRY_CODE TINYINT NOT NULL
);

ALTER TABLE PHONE
    ADD FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID);